create database mlp_334
use mlp_334
CREATE TABLE MENU_1(FOOD_ID INT PRIMARY KEY,FOOD_NAME VARCHAR(10),PRICE INT,DESC_CANTEEN VARCHAR(10));
CREATE TABLE CUSTOMER_1(CUST_ID INT PRIMARY KEY,CUST_NAME VARCHAR (10),CUST_ADDR VARCHAR(20));
CREATE TABLE VENDOR_1(VEND_ID INT PRIMARY KEY,VEND_NAME VARCHAR(10),VEND_ADDR VARCHAR(20));
CREATE TABLE ORDER_1(ORD_ID INT UNIQUE ,CUST_ID INT ,VEND_ID INT ,FOOD_ID INT ,CONSTRAINT CUSTID FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER_1(CUST_ID),CONSTRAINT VENDID FOREIGN KEY (VEND_ID) REFERENCES VENDOR_1(VEND_ID),CONSTRAINT FOODID FOREIGN KEY(FOOD_ID) REFERENCES MENU_1(FOOD_ID));
